import type { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiAdobephotoshop,
  SiAdobeillustrator,
  SiNotion,
  SiTypescript,
  SiTailwindcss,
  SiVercel,
  SiGooglegemini,
  SiGoogleanalytics,
  SiOpenai,
  SiPerplexity,
} from "react-icons/si";

import { CgMaze } from "react-icons/cg";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
  FaGoogle,
  FaPeopleGroup,
  FaConfluence,
  FaJira,
  FaReact,
  FaHotjar,
} from "react-icons/fa6";
import { noSSR } from "next/dynamic";
import { types } from "util";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  typescript: SiTypescript,
  tailwind: SiTailwindcss,
  vercel: SiVercel,
  hotjar: FaHotjar,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  react: FaReact,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  google: FaGoogle,
  maze: CgMaze,
  analytics: SiGoogleanalytics,
  lead: FaPeopleGroup,
  photoshop: SiAdobephotoshop,
  illustrator: SiAdobeillustrator,
  jira: FaJira,
  confluence: FaConfluence,
  notion: SiNotion,
  gemini: SiGooglegemini,
  chatgpt: SiOpenai,
  perplexity: SiPerplexity,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
