export const skillRatings = {
  categories: {
    "Scrum, Agile & DevOps": ["Professional Scrum Master (PSM I)", "Servant Leadership", "Lean-Agile Leadership", "Scrum Team Coaching",
              "Scaled Agile Framework (SAFe 6.0)", "SAFe Scrum Master Role", "Flow Metrics (SAFe 6.0)", "Team Syncs & Stand-Ups",
              "Agile Project Management","Conflict Resolution", "Facilitating Agile Ceremonies", "Kanban"],
    "Version Control & Collaboration Tools": ["Git", "GitHub", "GitLab", "Slack", "Jira", "Trello", "Microsoft Teams", "Code Collaboration"],
    "Frontend Development & UI Design": ["HTML", "CSS", "JavaScript", "Typescript",
              "React.js", "Next.js", "Tailwind", "Bootstrap", 
              "User-centric Design", "Accessibility Standards", "Responsive Design",
              "Modular UI Components", "Vite", "Remix", "GraphQL", "Wireframes"],
    "Backend Development & Cloud Expertise": ["Python", "C#", "Node.js", "Django Rest Framework", "Django", "SQL", "Flask",
              "RESTful APIs", "AWS S3", "Netlify", "Heroku", "Docker", "Kubernetes", "Gunicorn"],
    "Databases & Analysis & Data Visualisation": ["SQL","PostgreSQL", "SQLite", "BigQuery", "Data Migrations", 
              "Airbyte", "DagsterUI", "NumPy", "SciPy", "Matplotlib", "chart.js",
              "Entity-Relationship Diagrams", "ETL/ELT Pipelines"],
  },
  ratings: {
    HTML: 8,
    CSS: 7,
    JavaScript: 6, 
    Typescript: 6,     
    "React.js": 7, 
    "Next.js": 7, 
    Tailwind: 5, 
    Bootstrap: 3, 
    "User-centric Design": 6,
    "Accessibility Standards": 6,
    "Responsive Design": 6,
    "Modular UI Components": 6, 
    Vite: 6, 
    Remix: 6, 
    GraphQL: 6, 
    "Wireframes": 6,
    Python: 8, 
    "C#": 5, 
    "Node.js": 6, 
    "Django Rest Framework": 7, 
    Django: 7, 
    Flask: 7,
    "RESTful APIs": 7, 
    "AWS S3": 3, 
    Netlify: 6, 
    Heroku: 6, 
    Docker: 5, 
    Kubernetes: 5, 
    Gunicorn: 5,
    SQL: 6,
    PostgreSQL: 6, 
    SQLite: 6, 
    BigQuery: 5, 
    "Data Migrations": 5, 
    Airbyte: 5,
    DagsterUI: 5, 
    NumPy: 5, 
    SciPy: 5, 
    Matplotlib: 5, 
    "chart.js": 5,
    "Entity-Relationship Diagrams": 5, 
    "ETL/ELT Pipelines": 5,
    "Professional Scrum Master (PSM I)": 7, 
    "Servant Leadership": 8, 
    "Lean-Agile Leadership": 7, 
    "Scrum Team Coaching": 7,
    "Scaled Agile Framework (SAFe 6.0)": 7, 
    "SAFe Scrum Master Role": 6, 
    "Flow Metrics (SAFe 6.0)": 5, 
    "Team Syncs & Stand-Ups": 8,
    "Conflict Resolution": 8, 
    "Facilitating Agile Ceremonies": 8, 
    "Kanban": 7, 
    "CI/CD Pipelines": 6, 
    "CALMR Approach": 4,
    "Cloud Infrastructure": 3, 
    "Version Control": 7, 
    "Jira": 3, 
    "Trello": 6, 
    "Microsoft Teams": 8, 
    "Slack": 8,
    "Git": 8, 
    "GitHub": 8, 
    "GitLab": 5, 
    "Code Collaboration": 7, 
    "Agile Project Management": 7,
  },
};
