// Auto-generated by scripts/generate-manifest.js
export interface BlogPostMeta {
  title: string;
  slug: string;
  date: string;
  summary?: string;
  image?: string;
}

export const posts: BlogPostMeta[] = [
  {
    "title": "Welcome to teds.one!",
    "slug": "welcome",
    "date": "2025-07-10",
    "summary": "Welcome to the new teds.one website!",
    "image": "https://teds.one/api/og/generate?title=Welcome%20to%20teds.one!"
  }
];
